#include "MainMenuScene.h"

void MainMenuScene::SelectMode()
{
    int key;
    while (true)
    {
        system("cls");
        PrintMainMenu();
        key = _getch();
        if (key != 0)
        {
            system("cls");
            deckSelectScene.SelectDeck();
        }
    }
}

void MainMenuScene::PrintMainMenu() const
{
    int x = 40;
    int y = 20;
    // 1
    gotoxy(x, y);
    TextColor(BLACK, WHITE);
    std::cout << "¡¡¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡";

    // 2
    gotoxy(x, y + 1);
    TextColor(BLACK, WHITE);
    std::cout << "¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";

    //3
    gotoxy(x, y + 2);
    TextColor(BLACK, WHITE);
    std::cout << "¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";

    //4
    gotoxy(x, y + 3);
    TextColor(BLACK, WHITE);
    std::cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";

    //5
    gotoxy(x, y + 4);
    TextColor(BLACK, WHITE);
    std::cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";

    //6
    gotoxy(x, y + 5);
    TextColor(BLACK, WHITE);
    std::cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";

    //7
    gotoxy(x, y + 6);
    TextColor(BLACK, WHITE);
    std::cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";

    //8
    gotoxy(x, y + 7);
    TextColor(BLACK, WHITE);
    std::cout << "¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";

    //9
    gotoxy(x, y + 8);
    TextColor(BLACK, WHITE);
    std::cout << "¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";

    //10
    gotoxy(x, y + 9);
    TextColor(BLACK, WHITE);
    std::cout << "¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";

    //11
    gotoxy(x, y + 10);
    TextColor(BLACK, WHITE);
    std::cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";

    //12
    gotoxy(x, y + 11);
    TextColor(BLACK, WHITE);
    std::cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";

    //13
    gotoxy(x, y + 12);
    TextColor(BLACK, WHITE);
    std::cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";

    //14
    gotoxy(x, y + 13);
    TextColor(BLACK, WHITE);
    std::cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";

    //15
    gotoxy(x, y + 14);
    TextColor(BLACK, WHITE);
    std::cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";

    //16
    gotoxy(x, y + 15);
    TextColor(BLACK, WHITE);
    std::cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";

    //17
    gotoxy(x, y + 16);
    std::cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";

    //18
    gotoxy(x, y + 17);
    std::cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";

    //19
    gotoxy(x, y + 18);
    std::cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡";

    //20
    gotoxy(x, y + 19);
    std::cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡¡¡";
    TextColor(BLACK, WHITE);
    cout << "¡¡¡¡¡¡¡¡¡¡";
    TextColor(BLACK, BLACK);
    cout << "¡¡";

    gotoxy(x + 48, y + 21);
    TextColor(WHITE, BLACK);
    cout << "<Press Any Key to Start>";
}